version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: comentariosdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app1:
    build: .
    container_name: app1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/comentariosdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      JAVA_TOOL_OPTIONS: "-XX:MaxRAM=800m -XX:+UseContainerSupport"
    ports:
      - "8081:8080"

  app2:
    build: .
    container_name: app2
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/comentariosdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      JAVA_TOOL_OPTIONS: "-XX:MaxRAM=800m -XX:+UseContainerSupport"
    ports:
      - "8082:8080"

  nginx:
    image: nginx:latest
    container_name: nginx-balancer
    depends_on:
      - app1
      - app2
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata:
