version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: comentariosdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/comentariosdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      JAVA_TOOL_OPTIONS: "-XX:MaxRAM=800m -XX:+UseContainerSupport"
    ports:
      - "8080:8080"

volumes:
  pgdata:
